# Generated by Django 5.0.6 on 2024-06-26 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='card_number',
        ),
    ]
