# Generated by Django 5.0.6 on 2024-06-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_purchase_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='created_at',
        ),
        migrations.AddField(
            model_name='purchase',
            name='products',
            field=models.TextField(default=None),
        ),
    ]
