# Generated by Django 5.0.6 on 2024-06-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_remove_purchase_created_at_purchase_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='products',
            field=models.TextField(),
        ),
    ]
